### ISSUE TITLE
用示例数据和自己的数据运行Iterative pipeline出错

### ISSUE THREAD

**Issue by baiyun1985** [fanagislab/EndHiC#6]
尊敬的作者，您好：
感谢开发出这个好用的软件，我再运行中遇到点问题：研究物种有15条染色体，endhic.pl 跑完装出来16条，所以我想用Iterative [pipeline在跑一下，但是无论是示例数据还是我的数据，结果都报错，请帮忙看看咋回事，谢谢，我将主要的报错信息也黏贴在此：
（1）： Contact turning point: Illegal division by zero at /home/ug0824/endhic/EndHiC-master/turningpoint_by_lineartransform.pl line 88.
（2）： mkdir: cannot create directory ‘01.contig_end_contact_results’: File exists
mkdir: cannot create directory ‘02.GFA_contig_graph_results’: File exists
mkdir: cannot create directory [‘03.cluster_order_orient_results’:] File exists
mkdir: cannot create directory ‘04.summary_and_merging_results’: File exists
sh: 1: cannot create Round_C.04.summary_and_merging_results/z.EndHiC.C.results.summary.cluster: Directory nonexistent

**Comment by fanagislab** [comment]
您好！
    当前的16条，已经接近染色体数目了，只有最后的2条contig需要合并。建议直接跑 endhic_auto.pl   --rounds 2  可以自动跑两轮interative，看看能不能达到目的。 用法参见：https://github.com/fanagislab/EndHiC 


Name
    endhic_auto.pl -- automatically run multiple rounds of endhic.pl

Description
    Automatically run multiple rounds of endhic.pl, each round with
    parameters:

            A: " --minbinnum 5  --maxbinnum 25 "
            B: " --minbinnum 30 --maxbinnum 50 "
            C: " --minbinnum 55 --maxbinnum 75 "
            D: " --minbinnum 80 --maxbinnum 100 "
            E: " --minbinnum 105 --maxbinnum 125 "
            F: " --minbinnum 130 --maxbinnum 150 "
            G: " --minbinnum 155 --maxbinnum 175 "
            H: " --minbinnum 180 --maxbinnum 200 "
            .....................................
            .....................................
            .....................................

    You can choose the best result from all rounds, in which the cluster
    number equals or approximates the known chromosome number. Note that the
    assembly accuracy will decrease fastly as the running rounds growing.

Version
      Author: Fan Wei, ***@***.***
      Version: 1.0,  Date: 2022/3/17

Usage
      --rounds <int>  number of running rounds of endhic.pl , range 1 - 8, default = 3
      --verbose   output running progress information to screen  
      --help      output help information to screen

Exmple
      perl ~/fanwei/code/AGIS/EndHiC/endhic_auto.pl --rounds 3  contigs_all.len combined_100000_abs.bed combined_100000.matrix combined_100000_iced.matrix





***@***.***
 
发件人： baiyun1985
发送时间： 2022-04-11 15:35
收件人： fanagislab/EndHiC
抄送： Subscribed
主题： [fanagislab/EndHiC] 用示例数据和自己的数据运行Iterative pipeline出错 (Issue #6)
尊敬的作者，您好：
感谢开发出这个好用的软件，我再运行中遇到点问题：研究物种有15条染色体，endhic.pl 跑完装出来16条，所以我想用Iterative [pipeline在跑一下，但是无论是示例数据还是我的数据，结果都报错，请帮忙看看咋回事，谢谢，我将主要的报错信息也黏贴在此：
（1）： Contact turning point: Illegal division by zero at /home/ug0824/endhic/EndHiC-master/turningpoint_by_lineartransform.pl line 88.
（2）： mkdir: cannot create directory ‘01.contig_end_contact_results’: File exists
mkdir: cannot create directory ‘02.GFA_contig_graph_results’: File exists
mkdir: cannot create directory [‘03.cluster_order_orient_results’:] File exists
mkdir: cannot create directory ‘04.summary_and_merging_results’: File exists
sh: 1: cannot create Round_C.04.summary_and_merging_results/z.EndHiC.C.results.summary.cluster: Directory nonexistent

**Comment by baiyun1985** [comment]
> 

感谢您的答复，我跑两轮还是报同样的错误“endhic_auto.pl  --rounds 2 speciesA.chrom.size speciesA_1000000_abs.bed speciesA_1000000.matrix speciesA_1000000_iced.matrix”，但是用endhic.pl跑一轮就不会报错，请问这是什么原因呢？报错如下：
Contact turning point: Illegal division by zero at /data/implad/worksapce/04.HiC_assembly/EndHiC-master/turningpoint_by_lineartransform.pl line 88.

Contact turning point: Illegal division by zero at /data/implad/worksapce/04.HiC_assembly/EndHiC-master/turningpoint_by_lineartransform.pl line 88.

mkdir: cannot create directory ‘01.contig_end_contact_results’: File exists
mkdir: cannot create directory ‘02.GFA_contig_graph_results’: File exists
mkdir: cannot create directory ‘03.cluster_order_orient_results’: File exists
mkdir: cannot create directory ‘04.summary_and_merging_results’: File exists
sh: Round_B.04.summary_and_merging_results/z.EndHiC.B.results.summary.cluster: No such file or directory

**Comment by baiyun1985** [comment]
另外，我用示例数据画热图的时候，也报了错误，不知道别人是否遇到同样的问题，请指导一下。
(base) ug0824@gs82:~/endhic/EndHiC-master/Heatmap$ ../matrix2heatmap.py speciesA_1000000_abs.bed speciesA_1000000.matrix
Traceback (most recent call last):
  File "../matrix2heatmap.py", line 58, in <module>
    plt.colorbar(location="right", orientation="vertical", shrink=0.5)
  File "/pub/anaconda3/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2194, in colorbar
    ret = gcf().colorbar(mappable, cax=cax, ax=ax, **kw)
  File "/pub/anaconda3/lib/python3.8/site-packages/matplotlib/figure.py", line 2343, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, **cb_kw)
  File "/pub/anaconda3/lib/python3.8/site-packages/matplotlib/colorbar.py", line 1731, in colorbar_factory
    cb = Colorbar(cax, mappable, **kwargs)
  File "/pub/anaconda3/lib/python3.8/site-packages/matplotlib/colorbar.py", line 1225, in __init__
    ColorbarBase.__init__(self, ax, **kwargs)
  File "/pub/anaconda3/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'location'

**Comment by fanagislab** [comment]
Contact turning point: Illegal division by zero at /data/implad/worksapce/04.HiC_assembly/EndHiC-master/turningpoint_by_lineartransform.pl line 88

对应代码：
 ## Ajusted data divided by a times
$Count = @Data;
$Times = $Max / $Count;

说明这个程序运行时的输入文件*.CtgContact是空的，没有东西。 请检查下*.CtgContact文件，看是什么情况。


mkdir: cannot create directory ‘02.GFA_contig_graph_results’: File exists
运行程序之前，请把上一轮的残留目录和文件删掉，可能就不会有这类报错了。





***@***.***
 
发件人： baiyun1985
发送时间： 2022-04-12 12:00
收件人： fanagislab/EndHiC
抄送： fanwei; Comment
主题： Re: [fanagislab/EndHiC] 用示例数据和自己的数据运行Iterative pipeline出错 (Issue #6)
感谢您的答复，我跑两轮还是报同样的错误“endhic_auto.pl --rounds 2 speciesA.chrom.size speciesA_1000000_abs.bed speciesA_1000000.matrix speciesA_1000000_iced.matrix”，但是用endhic.pl跑一轮就不会报错，请问这是什么原因呢？报错如下：
Contact turning point: Illegal division by zero at /data/implad/worksapce/04.HiC_assembly/EndHiC-master/turningpoint_by_lineartransform.pl line 88.
Contact turning point: Illegal division by zero at /data/implad/worksapce/04.HiC_assembly/EndHiC-master/turningpoint_by_lineartransform.pl line 88.
mkdir: cannot create directory ‘01.contig_end_contact_results’: File exists
mkdir: cannot create directory ‘02.GFA_contig_graph_results’: File exists
mkdir: cannot create directory ‘03.cluster_order_orient_results’: File exists
mkdir: cannot create directory ‘04.summary_and_merging_results’: File exists
sh: Round_B.04.summary_and_merging_results/z.EndHiC.B.results.summary.cluster: No such file or directory
